#!/bin/sh

if [ $# -ne 1 ]; then
    echo "USAGE: $0 host"
    exit 1
fi

TARGET=$1

RESULT=$(ping -n -c 1 $TARGET)
STATUS=$?

case $STATUS in
    0)
        exit 0
    ;;
    1)
        echo Could not ping $TARGET
        echo $RESULT
        exit 1
    ;;
    2 | *)
        echo Unexpected error pinging $TARGET
        echo $RESULT
        exit 2
    ;;
esac
