#!/bin/bash

if [ $# -ne 2 ]; then
    echo "USAGE: $0 host port"
    exit 1
fi

set -u
HOST=$1
PORT=$2

TIMEOUT=10

RESULT=$(nc -w $TIMEOUT -z $HOST $PORT)

if [[ $RESULT =~ succeeded! ]]; then
    exit 0
else
    echo "Could not reach the service on ${HOST}:${PORT}"
    echo $RESULT
    exit 1
fi
